# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position

    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true